version: "3.9"

services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://root:password@mongodb:27017/brand-tracker?authSource=admin
      NODE_ENV: development
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL= http://localhost:5000
    depends_on:
      - backend

volumes:
  mongo_data:
